site_name: Docs
site_url: https://github.com/marosko89/mkdocs
site_description: Markdown env.
site_author: Martin Florek

# Repository
repo_name: marosko89/mkdocs
repo_url: https://github.com/marosko89/mkdocs
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 - 2023 Martin Florek

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.png
  features:
    - navigation.footer
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest

# # Plugins
# plugins:
#   - search:
#       separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
extra:
  version:
    provider: mike

# Page tree
nav:
  - Home: index.md
  - ChatGPT:
      - User Guide: q.md
